/* EDITH: motor local de comandos. No requiere IA ni claves privadas. */
const CLAVE_HISTORIAL="edith_historial_v1", CLAVE_CONFIG="edith_config_v1", CLAVE_MEMORIA="edith_memoria_v1", CLAVE_TAREAS="edith_tareas_v1";
const estado={voz:true,nombre:"EDITH",escuchando:false,reconocimiento:null,temporizador:null,cronometro:null,modo:"normal",apagada:false};
const $=s=>document.querySelector(s); const el={mensajes:$("#messages"),form:$("#messageForm"),entrada:$("#messageInput"),microfono:$("#micButton"),micStatus:$("#micStatus"),procesando:$("#processing"),voz:$("#voiceToggle"),borrar:$("#clearButton"),config:$("#settingsButton"),panel:$("#settingsPanel"),nombre:$("#assistantName"),guardar:$("#saveSettings"),titulo:$("#assistantTitle"),reloj:$("#clock"),calendario:$("#calendar"),mes:$("#calendarMonth")};
function leer(k,f){try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}} function guardar(k,v){localStorage.setItem(k,JSON.stringify(v))}
function agregar(autor,texto,guardarChat=true){const n=document.createElement("div");n.className=`message ${autor}`;n.dataset.autor=autor;n.innerHTML=`<div class="bubble"><span class="meta">${autor==="user"?"USTED":estado.nombre}</span><span class="content"></span></div>`;n.querySelector(".content").textContent=texto;el.mensajes.appendChild(n);el.mensajes.scrollTop=el.mensajes.scrollHeight;if(guardarChat)guardar(CLAVE_HISTORIAL,[...document.querySelectorAll(".message")].map(x=>({autor:x.dataset.autor,texto:x.querySelector(".content").textContent})))}
function hablar(t){if(!estado.voz||!("speechSynthesis"in window))return;speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(t);u.lang="es-AR";u.rate=.96;u.pitch=.92;speechSynthesis.speak(u)}
function responder(t){agregar("assistant",t);hablar(t)}
function listaComandos(){return `COMANDOS LOCALES DISPONIBLES\n\nBÁSICOS: ayuda, estado, hola, buenos días, buenas noches, quién eres, quién soy, versión, reiniciar, apagar.\nMEMORIA: recuerda [dato], memoria, olvida [dato], limpia memoria, preferencias, modo memoria.\nORGANIZACIÓN: fecha, hora, día, tareas, nueva tarea [tarea], completa [tarea], elimina tarea [tarea].\nTIEMPO: temporizador 5 minutos, cancelar temporizador, cronómetro, detener cronómetro, cuenta atrás 10 segundos, cuánto falta.\nHERRAMIENTAS: calcula [operación], porcentaje [número] de [total], promedio [números], máximo [números], mínimo [números], random, lanza un dado, elige [opciones].\nMODOS: modo jarvis, modo silencioso, modo voz, modo privado, modo estudio, modo desarrollador, diagnóstico, protocolo edith.\nDISPOSITIVO: batería, wifi, abrir navegador, abrir música.\n\nLos comandos de IA, noticias, clima, mapas y búsquedas requieren servicios externos.`}
function duracion(s){const m=s.match(/(\d+(?:[.,]\d+)?)\s*(segundos?|minutos?|horas?)/i);if(!m)return null;let n=Number(m[1].replace(",","."));if(/hora/i.test(m[2]))n*=3600;else if(/minuto/i.test(m[2]))n*=60;return Math.round(n*1000)}
function tareas(){return leer(CLAVE_TAREAS,[])}
function ejecutar(mensaje){let m=mensaje.trim(), x=m.toLowerCase().replace(/^edith[,:]?\s*/,"").trim(); if(!x)return "Sí, señor. Estoy escuchando.";
 if(x==="ayuda"||x.includes("todos los comandos"))return listaComandos();
 if(x==="estado")return `Estado de ${estado.nombre}: ONLINE. Modo ${estado.modo}. Voz ${estado.voz?"activada":"desactivada"}. Memoria local operativa. Micrófono ${("SpeechRecognition"in window||"webkitSpeechRecognition"in window)?"compatible":"no compatible"}.`;
 if(/^(hola|buenas tardes)$/.test(x))return `Buenas tardes, señor. ${estado.nombre} en línea y lista para servirlo.`;
 if(x==="buenos días"||x==="buenos dias")return "Buenos días, señor. Agenda despejada en esta demo; el café, lamentablemente, sigue fuera de mis permisos.";
 if(x==="buenas noches")return "Buenas noches, señor. Sistema en modo tranquilo. No apagaré las estrellas por ahora.";
 if(x.includes("quién eres")||x.includes("quien eres"))return "Soy EDITH, su asistente personal local. Puedo ejecutar comandos en el navegador, guardar memoria y ayudarlo sin depender de una IA.";
 if(x.includes("quién soy")||x.includes("quien soy"))return "Usted es el señor Franchesco Virgilini. Así está configurado en esta instalación.";
 if(x==="versión"||x==="version")return "EDITH versión 2.5.1, motor local de comandos.";
 if(x==="reiniciar")return "Módulos locales reiniciados, señor. La elegancia sigue intacta.";
 if(x==="apagar"){estado.apagada=true;return "Modo asistente desactivado temporalmente. Para reactivarme, escriba: edith hola."}
 if(estado.apagada){if(x==="hola"){estado.apagada=false;return "Sistemas reactivados, señor."}return "Estoy apagada temporalmente. Escriba: edith hola."}
 if(x.startsWith("recuerda ")&&!x.startsWith("recuerda qué")){let d=m.replace(/^edith[,:]?\s*recuerda\s+/i,"").trim();let mem=leer(CLAVE_MEMORIA,[]);mem.push({texto:d,fecha:new Date().toLocaleString("es-AR")});guardar(CLAVE_MEMORIA,mem);return `Guardado en memoria local: “${d}”.`}
 if(x==="memoria"){let mem=leer(CLAVE_MEMORIA,[]);return mem.length?"MEMORIA LOCAL:\n"+mem.map((a,i)=>`${i+1}. ${a.texto}`).join("\n"):"La memoria local está vacía, señor."}
 if(x.startsWith("olvida ")){let q=x.replace(/^olvida\s+/i,"");let mem=leer(CLAVE_MEMORIA,[]);let antes=mem.length;mem=mem.filter(a=>!a.texto.toLowerCase().includes(q));guardar(CLAVE_MEMORIA,mem);return antes===mem.length?"No encontré ese dato en la memoria.":"Dato eliminado de la memoria local."}
 if(x==="limpia memoria"){localStorage.removeItem(CLAVE_MEMORIA);return "Memoria local eliminada, señor."}
 if(x==="preferencias")return `Preferencias: nombre ${estado.nombre}; voz ${estado.voz?"activada":"desactivada"}; modo ${estado.modo}; almacenamiento local ${localStorage?"disponible":"no disponible"}.`;
 if(x==="modo memoria")return "La memoria se administra desde el navegador mediante LocalStorage. Puede borrarla con: edith limpia memoria.";
 if(x==="fecha")return `Hoy es ${new Date().toLocaleDateString("es-AR",{dateStyle:"full"})}, señor.`;
 if(x==="hora")return `La hora local es ${new Date().toLocaleTimeString("es-AR",{hour:"2-digit",minute:"2-digit",second:"2-digit"}), señor.`;
 if(x==="día"||x==="dia")return `Hoy es ${new Date().toLocaleDateString("es-AR",{weekday:"long"})}.`;
 if(x==="tareas"){let ts=tareas();return ts.length?"TAREAS:\n"+ts.map((t,i)=>`${i+1}. ${t.completa?"✓":"□"} ${t.texto}`).join("\n"):"No hay tareas guardadas."}
 if(x.startsWith("nueva tarea ")){let texto=m.replace(/^edith[,:]?\s*nueva tarea\s+/i,"").trim(),ts=tareas();if(!texto)return "Indique el texto de la tarea, señor.";ts.push({texto,completa:false});guardar(CLAVE_TAREAS,ts);return `Tarea creada: “${texto}”.`}
 if(x.startsWith("completa ")){let q=x.replace(/^completa\s+/i,"");let ts=tareas(),t=ts.find(a=>a.texto.toLowerCase().includes(q));if(!t)return "No encontré esa tarea.";t.completa=true;guardar(CLAVE_TAREAS,ts);return `Tarea completada: “${t.texto}”.`}
 if(x.startsWith("elimina tarea ")){let q=x.replace(/^elimina tarea\s+/i,"");let ts=tareas(),n=ts.length;ts=ts.filter(a=>!a.texto.toLowerCase().includes(q));guardar(CLAVE_TAREAS,ts);return n===ts.length?"No encontré esa tarea.":"Tarea eliminada."}
 if(x.startsWith("temporizador ")||x.startsWith("cuenta atrás ")||x.startsWith("cuenta atras ")){let ms=duracion(x);if(!ms)return "Indique una duración, por ejemplo: edith temporizador 5 minutos.";clearTimeout(estado.temporizador);estado.temporizador=setTimeout(()=>{responder("Temporizador finalizado, señor.")},ms);estado.temporizadorHasta=Date.now()+ms;return `Temporizador iniciado por ${Math.round(ms/1000)} segundos.`}
 if(x==="cancelar temporizador"){clearTimeout(estado.temporizador);estado.temporizador=null;return "Temporizador cancelado."}
 if(x==="cuánto falta"||x==="cuanto falta"){if(!estado.temporizadorHasta)return "No hay un temporizador activo.";return `Faltan aproximadamente ${Math.max(0,Math.ceil((estado.temporizadorHasta-Date.now())/1000))} segundos.`}
 if(x==="cronómetro"||x==="cronometro"){estado.cronometro=Date.now();return "Cronómetro iniciado."}
 if(x.includes("detener cronómetro")||x.includes("detener cronometro")){if(!estado.cronometro)return "No hay un cronómetro activo.";let s=Math.floor((Date.now()-estado.cronometro)/1000);estado.cronometro=null;return `Cronómetro detenido: ${s} segundos.`}
 if(x.startsWith("calcula ")){let op=x.replace(/^calcula\s+/i,"").replace(/,/g,".");if(!/^[0-9+\-*/().%\s]+$/.test(op))return "Solo puedo calcular operaciones numéricas simples por seguridad.";try{return `Resultado: ${Function(`"use strict";return (${op})`)()}`}catch{return "No pude resolver esa operación."}}
 if(x.startsWith("porcentaje ")){let a=x.match(/([\d.,]+).*?([\d.,]+)/);if(!a)return "Use: edith porcentaje 20 de 150.";return `Resultado: ${(Number(a[1].replace(",","."))*Number(a[2].replace(",","."))/100).toFixed(2)}`}
 if(/^(promedio|máximo|máximo|mínimo|random|lanza un dado)/.test(x)){let nums=(x.match(/-?\d+(?:[.,]\d+)?/g)||[]).map(n=>Number(n.replace(",",".")));if(x==="random")return `Número aleatorio: ${Math.floor(Math.random()*100)+1}.`;if(x.includes("dado"))return `Resultado del dado: ${Math.floor(Math.random()*6)+1}.`;if(!nums.length)return "Indique números separados por espacios.";if(x.startsWith("promedio"))return `Promedio: ${nums.reduce((a,b)=>a+b,0)/nums.length}.`;if(x.startsWith("máximo"))return `Máximo: ${Math.max(...nums)}.`;return `Mínimo: ${Math.min(...nums)}.`}
 if(x.startsWith("elige ")){let opciones=m.replace(/^edith[,:]?\s*elige\s+/i,"").split(/,|\s+o\s+/i).map(a=>a.trim()).filter(Boolean);return opciones.length?`Elijo: ${opciones[Math.floor(Math.random()*opciones.length)]}.`:"Indique las opciones separadas por comas."}
 if(x==="batería"||x==="bateria"){if(!navigator.getBattery)return "Su navegador no permite consultar la batería desde esta página.";return "Consultando batería..."}
 if(x==="wifi")return navigator.onLine?"Conectividad del navegador: en línea. No puedo controlar el Wi‑Fi del dispositivo desde una página web.":"El navegador informa que está sin conexión.";
 if(x.includes("abrir navegador")){window.open("https://www.google.com","_blank","noopener");return "Abrí una pestaña del navegador, señor."}
 if(x.includes("abrir música")||x.includes("abrir musica")){window.open("https://music.youtube.com","_blank","noopener");return "Abrí el reproductor web de música."}
 if(/^modo /.test(x)){let modo=x.replace(/^modo\s+/,"");if(modo.includes("voz")){estado.voz=true;actualizarVoz();return "Modo voz activado."}if(modo.includes("silencioso")){estado.voz=false;actualizarVoz();return "Modo silencioso activado."}estado.modo=modo;return `Modo ${modo} activado, señor.`}
 if(x==="diagnóstico"||x==="diagnostico")return `DIAGNÓSTICO:\n✓ Interfaz cargada\n✓ LocalStorage disponible\n✓ Voz ${("speechSynthesis"in window)?"disponible":"no disponible"}\n✓ Reconocimiento ${("SpeechRecognition"in window||"webkitSpeechRecognition"in window)?"disponible":"no disponible"}\n✓ Conexión ${navigator.onLine?"activa":"sin conexión"}`;
 if(x==="protocolo edith")return `Protocolo EDITH activo, señor. Sistema en línea, memoria local operativa y ${listaComandos().split("\n").length} líneas de comandos disponibles.`;
 if(/^(clima|noticias|busca|buscar|mapa|wikipedia|responde|explica|resume|analiza|traduce|corrige|escribe)/.test(x))return "Ese comando requiere una conexión a un servicio externo o una IA. La versión local no inventará resultados, señor.";
 return `He recibido “${m}”. Pruebe “edith ayuda” para ver los comandos locales disponibles.`}
function enviar(m){let t=m.trim();if(!t)return;agregar("user",t);el.entrada.value="";el.procesando.hidden=false;setTimeout(()=>{el.procesando.hidden=true;responder(ejecutar(t))},250)}
function actualizarVoz(){el.voz.textContent=estado.voz?"🔊 Voz: activada":"🔇 Voz: desactivada";guardar(CLAVE_CONFIG,{nombre:estado.nombre,voz:estado.voz})}
function iniciarMicro(){const R=window.SpeechRecognition||window.webkitSpeechRecognition;if(!R){el.micStatus.textContent="Su navegador no admite reconocimiento de voz.";return}if(estado.escuchando){estado.reconocimiento.stop();return}const r=estado.reconocimiento=new R();r.lang="es-AR";r.interimResults=false;r.onstart=()=>{estado.escuchando=true;el.microfono.textContent="⏹️";el.micStatus.textContent="Escuchando, señor..."};r.onresult=e=>{el.entrada.value=e.results[0][0].transcript;enviar(el.entrada.value)};r.onerror=()=>el.micStatus.textContent="No pude interpretar el audio. Intente nuevamente.";r.onend=()=>{estado.escuchando=false;el.microfono.textContent="🎙️"};try{r.start()}catch{el.micStatus.textContent="El micrófono está ocupado."}}
function calendario(){const d=new Date();el.mes.textContent=d.toLocaleDateString("es-AR",{month:"short"}).toUpperCase();["L","M","X","J","V","S","D"].forEach(v=>{const b=document.createElement("b");b.textContent=v;el.calendario.appendChild(b)});let hueco=(new Date(d.getFullYear(),d.getMonth(),1).getDay()+6)%7;for(let i=0;i<hueco;i++)el.calendario.appendChild(document.createElement("span"));for(let i=1;i<=new Date(d.getFullYear(),d.getMonth()+1,0).getDate();i++){const s=document.createElement("span");s.textContent=i;if(i===d.getDate())s.className="today";el.calendario.appendChild(s)}}
function cargar(){const c=leer(CLAVE_CONFIG,{});estado.nombre=c.nombre||"EDITH";estado.voz=c.voz!==false;el.nombre.value=estado.nombre;el.titulo.textContent=estado.nombre;let h=leer(CLAVE_HISTORIAL,[]);if(h.length)h.forEach(a=>agregar(a.autor,a.texto,false));else agregar("assistant",`Buenos días, señor. Soy ${estado.nombre}. Motor local de comandos en línea.`);actualizarVoz()}
el.form.addEventListener("submit",e=>{e.preventDefault();enviar(el.entrada.value)});el.microfono.addEventListener("click",iniciarMicro);el.voz.addEventListener("click",()=>{estado.voz=!estado.voz;if(!estado.voz&&"speechSynthesis"in window)speechSynthesis.cancel();actualizarVoz()});el.borrar.addEventListener("click",()=>{if(confirm("¿Borrar todo el historial, señor?")){localStorage.removeItem(CLAVE_HISTORIAL);el.mensajes.innerHTML="";agregar("assistant","Historial eliminado. Empezamos de nuevo, señor.")}});el.config.addEventListener("click",()=>el.panel.hidden=!el.panel.hidden);el.guardar.addEventListener("click",()=>{const n=el.nombre.value.trim();if(!n)return alert("Escriba un nombre válido, señor.");estado.nombre=n;el.titulo.textContent=n;el.panel.hidden=true;actualizarVoz()});document.querySelectorAll("[data-message]").forEach(b=>b.addEventListener("click",()=>enviar(b.dataset.message)));cargar();calendario();setInterval(()=>{el.reloj.textContent=new Date().toLocaleTimeString("es-AR")},1000);
